// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDODC_kyVCAR75L5DNh1KC_545ENW_2kDA',
    appId: '1:359838751950:web:21fbf5557e643b9e9b449f',
    messagingSenderId: '359838751950',
    projectId: 'cw-enerji-65a95',
    authDomain: 'cw-enerji-65a95.firebaseapp.com',
    databaseURL: 'https://cw-enerji-65a95-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cw-enerji-65a95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAiYskCjtPYc75a71r04AH_Rg8uHKUrnI',
    appId: '1:359838751950:android:e97c7968c58305e79b449f',
    messagingSenderId: '359838751950',
    projectId: 'cw-enerji-65a95',
    databaseURL: 'https://cw-enerji-65a95-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cw-enerji-65a95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNO4Yighs3D9-sKyUrr-3CKAJWjPVa2rU',
    appId: '1:359838751950:ios:939a42ff9bc270a59b449f',
    messagingSenderId: '359838751950',
    projectId: 'cw-enerji-65a95',
    databaseURL: 'https://cw-enerji-65a95-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cw-enerji-65a95.appspot.com',
    iosClientId: '359838751950-ks7t45dq0fbpboool5e2i2crgekc2ujf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseRealtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNO4Yighs3D9-sKyUrr-3CKAJWjPVa2rU',
    appId: '1:359838751950:ios:cba016692cae31809b449f',
    messagingSenderId: '359838751950',
    projectId: 'cw-enerji-65a95',
    databaseURL: 'https://cw-enerji-65a95-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cw-enerji-65a95.appspot.com',
    iosClientId: '359838751950-omo24082t1b80agfe2g6r1ehbg0gc163.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseRealtime.RunnerTests',
  );
}
